//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export interface ILemonTaskManagementApiClient {
    authentication_Login(command: LoginCommand): Promise<ApiResponseOfLoginResponse>;
    userBoards_GetUserBoards(userIdPath: string, userIdQuery: string | undefined, skip: number | undefined, take: number | undefined): Promise<ApiResponseOfGetUserBoardsResponse>;
    userBoards_GetUserBoard(userId: string, boardId: string): Promise<ApiResponseOfGetUserBoardResponse>;
    userBoards_CreateCard(userId: string, boardId: string, command: CreateCardCommand): Promise<ApiResponseOfCreateCardResponse>;
    userBoards_UpdateCard(userId: string, boardId: string, cardId: string, command: UpdateCardCommand): Promise<ApiResponseOfUpdateCardResponse>;
    userBoards_MoveCard(userId: string, boardId: string, cardId: string, command: MoveCardCommand): Promise<ApiResponseOfMoveCardResponse>;
    users_GetUser(id: string): Promise<ApiResponseOfGetUserResponse>;
    users_GetUsers(nameContains: string | null | undefined, emailContains: string | null | undefined, skip: number | undefined, take: number | undefined): Promise<ApiResponseOfGetUsersResponse>;
}

export class LemonTaskManagementApiClient implements ILemonTaskManagementApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    authentication_Login(command: LoginCommand, cancelToken?: CancelToken): Promise<ApiResponseOfLoginResponse> {
        let url_ = this.baseUrl + "/api/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAuthentication_Login(_response);
        });
    }

    protected processAuthentication_Login(response: AxiosResponse): Promise<ApiResponseOfLoginResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfLoginResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfLoginResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400 = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401 = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("A server side error occurred.", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfLoginResponse>(null as any);
    }

    userBoards_GetUserBoards(userIdPath: string, userIdQuery: string | undefined, skip: number | undefined, take: number | undefined, cancelToken?: CancelToken): Promise<ApiResponseOfGetUserBoardsResponse> {
        let url_ = this.baseUrl + "/api/users/{userId}/boards?";
        if (userIdPath === undefined || userIdPath === null)
            throw new Error("The parameter 'userIdPath' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userIdPath));
        if (userIdQuery === null)
            throw new Error("The parameter 'userIdQuery' cannot be null.");
        else if (userIdQuery !== undefined)
            url_ += "UserId=" + encodeURIComponent("" + userIdQuery) + "&";
        if (skip === null)
            throw new Error("The parameter 'skip' cannot be null.");
        else if (skip !== undefined)
            url_ += "Skip=" + encodeURIComponent("" + skip) + "&";
        if (take === null)
            throw new Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "Take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUserBoards_GetUserBoards(_response);
        });
    }

    protected processUserBoards_GetUserBoards(response: AxiosResponse): Promise<ApiResponseOfGetUserBoardsResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfGetUserBoardsResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfGetUserBoardsResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfGetUserBoardsResponse>(null as any);
    }

    userBoards_GetUserBoard(userId: string, boardId: string, cancelToken?: CancelToken): Promise<ApiResponseOfGetUserBoardResponse> {
        let url_ = this.baseUrl + "/api/users/{userId}/boards/{boardId}";
        if (userId === undefined || userId === null)
            throw new Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (boardId === undefined || boardId === null)
            throw new Error("The parameter 'boardId' must be defined.");
        url_ = url_.replace("{boardId}", encodeURIComponent("" + boardId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUserBoards_GetUserBoard(_response);
        });
    }

    protected processUserBoards_GetUserBoard(response: AxiosResponse): Promise<ApiResponseOfGetUserBoardResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfGetUserBoardResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfGetUserBoardResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfGetUserBoardResponse>(null as any);
    }

    userBoards_CreateCard(userId: string, boardId: string, command: CreateCardCommand, cancelToken?: CancelToken): Promise<ApiResponseOfCreateCardResponse> {
        let url_ = this.baseUrl + "/api/users/{userId}/boards/{boardId}/cards";
        if (userId === undefined || userId === null)
            throw new Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (boardId === undefined || boardId === null)
            throw new Error("The parameter 'boardId' must be defined.");
        url_ = url_.replace("{boardId}", encodeURIComponent("" + boardId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUserBoards_CreateCard(_response);
        });
    }

    protected processUserBoards_CreateCard(response: AxiosResponse): Promise<ApiResponseOfCreateCardResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201 = _responseText;
            result201 = ApiResponseOfCreateCardResponse.fromJS(resultData201);
            return Promise.resolve<ApiResponseOfCreateCardResponse>(result201);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400 = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfCreateCardResponse>(null as any);
    }

    userBoards_UpdateCard(userId: string, boardId: string, cardId: string, command: UpdateCardCommand, cancelToken?: CancelToken): Promise<ApiResponseOfUpdateCardResponse> {
        let url_ = this.baseUrl + "/api/users/{userId}/boards/{boardId}/cards/{cardId}";
        if (userId === undefined || userId === null)
            throw new Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (boardId === undefined || boardId === null)
            throw new Error("The parameter 'boardId' must be defined.");
        url_ = url_.replace("{boardId}", encodeURIComponent("" + boardId));
        if (cardId === undefined || cardId === null)
            throw new Error("The parameter 'cardId' must be defined.");
        url_ = url_.replace("{cardId}", encodeURIComponent("" + cardId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUserBoards_UpdateCard(_response);
        });
    }

    protected processUserBoards_UpdateCard(response: AxiosResponse): Promise<ApiResponseOfUpdateCardResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfUpdateCardResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfUpdateCardResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400 = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404 = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfUpdateCardResponse>(null as any);
    }

    userBoards_MoveCard(userId: string, boardId: string, cardId: string, command: MoveCardCommand, cancelToken?: CancelToken): Promise<ApiResponseOfMoveCardResponse> {
        let url_ = this.baseUrl + "/api/users/{userId}/boards/{boardId}/cards/{cardId}/move";
        if (userId === undefined || userId === null)
            throw new Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (boardId === undefined || boardId === null)
            throw new Error("The parameter 'boardId' must be defined.");
        url_ = url_.replace("{boardId}", encodeURIComponent("" + boardId));
        if (cardId === undefined || cardId === null)
            throw new Error("The parameter 'cardId' must be defined.");
        url_ = url_.replace("{cardId}", encodeURIComponent("" + cardId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUserBoards_MoveCard(_response);
        });
    }

    protected processUserBoards_MoveCard(response: AxiosResponse): Promise<ApiResponseOfMoveCardResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfMoveCardResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfMoveCardResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400 = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfMoveCardResponse>(null as any);
    }

    users_GetUser(id: string, cancelToken?: CancelToken): Promise<ApiResponseOfGetUserResponse> {
        let url_ = this.baseUrl + "/api/users/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUsers_GetUser(_response);
        });
    }

    protected processUsers_GetUser(response: AxiosResponse): Promise<ApiResponseOfGetUserResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfGetUserResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfGetUserResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfGetUserResponse>(null as any);
    }

    users_GetUsers(nameContains: string | null | undefined, emailContains: string | null | undefined, skip: number | undefined, take: number | undefined, cancelToken?: CancelToken): Promise<ApiResponseOfGetUsersResponse> {
        let url_ = this.baseUrl + "/api/users?";
        if (nameContains !== undefined && nameContains !== null)
            url_ += "NameContains=" + encodeURIComponent("" + nameContains) + "&";
        if (emailContains !== undefined && emailContains !== null)
            url_ += "EmailContains=" + encodeURIComponent("" + emailContains) + "&";
        if (skip === null)
            throw new Error("The parameter 'skip' cannot be null.");
        else if (skip !== undefined)
            url_ += "Skip=" + encodeURIComponent("" + skip) + "&";
        if (take === null)
            throw new Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "Take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUsers_GetUsers(_response);
        });
    }

    protected processUsers_GetUsers(response: AxiosResponse): Promise<ApiResponseOfGetUsersResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = ApiResponseOfGetUsersResponse.fromJS(resultData200);
            return Promise.resolve<ApiResponseOfGetUsersResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponseOfGetUsersResponse>(null as any);
    }
}

export class ApiResponseOfLoginResponse implements IApiResponseOfLoginResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: LoginResponse | undefined;

    constructor(data?: IApiResponseOfLoginResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? LoginResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfLoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfLoginResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfLoginResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: LoginResponse | undefined;
}

export class ApiError implements IApiError {
    message?: string;
    details?: string;
    errors?: ValidationError[];

    constructor(data?: IApiError) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.message = _data["message"];
            this.details = _data["details"];
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ValidationError.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ApiError {
        data = typeof data === 'object' ? data : {};
        let result = new ApiError();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["message"] = this.message;
        data["details"] = this.details;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IApiError {
    message?: string;
    details?: string;
    errors?: ValidationError[];
}

export class ValidationError implements IValidationError {
    field?: string;
    message?: string;

    constructor(data?: IValidationError) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.field = _data["field"];
            this.message = _data["message"];
        }
    }

    static fromJS(data: any): ValidationError {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationError();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["field"] = this.field;
        data["message"] = this.message;
        return data;
    }
}

export interface IValidationError {
    field?: string;
    message?: string;
}

export class Response implements IResponse {
    success?: boolean;
    message?: string;
    errors?: ErrorDto[];

    constructor(data?: IResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ErrorDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Response {
        data = typeof data === 'object' ? data : {};
        let result = new Response();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IResponse {
    success?: boolean;
    message?: string;
    errors?: ErrorDto[];
}

export class LoginResponse extends Response implements ILoginResponse {
    data?: LoginDto | undefined;

    constructor(data?: ILoginResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? LoginDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): LoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface ILoginResponse extends IResponse {
    data?: LoginDto | undefined;
}

export class LoginDto implements ILoginDto {
    userId?: string;
    username?: string | undefined;
    email?: string | undefined;
    token?: string | undefined;
    expiresAt?: Date;

    constructor(data?: ILoginDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.username = _data["username"];
            this.email = _data["email"];
            this.token = _data["token"];
            this.expiresAt = _data["expiresAt"] ? new Date(_data["expiresAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): LoginDto {
        data = typeof data === 'object' ? data : {};
        let result = new LoginDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["username"] = this.username;
        data["email"] = this.email;
        data["token"] = this.token;
        data["expiresAt"] = this.expiresAt ? this.expiresAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface ILoginDto {
    userId?: string;
    username?: string | undefined;
    email?: string | undefined;
    token?: string | undefined;
    expiresAt?: Date;
}

export class ErrorDto implements IErrorDto {
    property?: string;
    message?: string;

    constructor(data?: IErrorDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.property = _data["property"];
            this.message = _data["message"];
        }
    }

    static fromJS(data: any): ErrorDto {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["property"] = this.property;
        data["message"] = this.message;
        return data;
    }
}

export interface IErrorDto {
    property?: string;
    message?: string;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class LoginCommand implements ILoginCommand {
    username?: string | undefined;
    password?: string | undefined;

    constructor(data?: ILoginCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginCommand {
        data = typeof data === 'object' ? data : {};
        let result = new LoginCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginCommand {
    username?: string | undefined;
    password?: string | undefined;
}

export class ApiResponseOfGetUserBoardsResponse implements IApiResponseOfGetUserBoardsResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserBoardsResponse | undefined;

    constructor(data?: IApiResponseOfGetUserBoardsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? GetUserBoardsResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfGetUserBoardsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfGetUserBoardsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfGetUserBoardsResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserBoardsResponse | undefined;
}

export class ResponseOfListOfUserBoardDto extends Response implements IResponseOfListOfUserBoardDto {
    data?: UserBoardDto[] | undefined;

    constructor(data?: IResponseOfListOfUserBoardDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(UserBoardDto.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): ResponseOfListOfUserBoardDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfListOfUserBoardDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item ? item.toJSON() : <any>undefined);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfListOfUserBoardDto extends IResponse {
    data?: UserBoardDto[] | undefined;
}

export class GetUserBoardsResponse extends ResponseOfListOfUserBoardDto implements IGetUserBoardsResponse {

    constructor(data?: IGetUserBoardsResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): GetUserBoardsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetUserBoardsResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IGetUserBoardsResponse extends IResponseOfListOfUserBoardDto {
}

export class UserBoardDto implements IUserBoardDto {
    userId?: string;
    user?: UserDto | undefined;
    boardId?: string;
    board?: BoardDto | undefined;
    createdAt?: Date;

    constructor(data?: IUserBoardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.user = _data["user"] ? UserDto.fromJS(_data["user"]) : <any>undefined;
            this.boardId = _data["boardId"];
            this.board = _data["board"] ? BoardDto.fromJS(_data["board"]) : <any>undefined;
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): UserBoardDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserBoardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["user"] = this.user ? this.user.toJSON() : <any>undefined;
        data["boardId"] = this.boardId;
        data["board"] = this.board ? this.board.toJSON() : <any>undefined;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IUserBoardDto {
    userId?: string;
    user?: UserDto | undefined;
    boardId?: string;
    board?: BoardDto | undefined;
    createdAt?: Date;
}

export class UserDto implements IUserDto {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    createdAt?: Date;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.username = _data["username"];
            this.email = _data["email"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["username"] = this.username;
        data["email"] = this.email;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IUserDto {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    createdAt?: Date;
}

export class BoardDto implements IBoardDto {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    createdAt?: Date;
    columns?: BoardColumnDto[] | undefined;

    constructor(data?: IBoardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            if (Array.isArray(_data["columns"])) {
                this.columns = [] as any;
                for (let item of _data["columns"])
                    this.columns!.push(BoardColumnDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BoardDto {
        data = typeof data === 'object' ? data : {};
        let result = new BoardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        if (Array.isArray(this.columns)) {
            data["columns"] = [];
            for (let item of this.columns)
                data["columns"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IBoardDto {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    createdAt?: Date;
    columns?: BoardColumnDto[] | undefined;
}

export class BoardColumnDto implements IBoardColumnDto {
    id?: string;
    boardId?: string;
    name?: string | undefined;
    order?: number;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    cards?: CardDto[] | undefined;

    constructor(data?: IBoardColumnDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.boardId = _data["boardId"];
            this.name = _data["name"];
            this.order = _data["order"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
            if (Array.isArray(_data["cards"])) {
                this.cards = [] as any;
                for (let item of _data["cards"])
                    this.cards!.push(CardDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BoardColumnDto {
        data = typeof data === 'object' ? data : {};
        let result = new BoardColumnDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["boardId"] = this.boardId;
        data["name"] = this.name;
        data["order"] = this.order;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        if (Array.isArray(this.cards)) {
            data["cards"] = [];
            for (let item of this.cards)
                data["cards"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IBoardColumnDto {
    id?: string;
    boardId?: string;
    name?: string | undefined;
    order?: number;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    cards?: CardDto[] | undefined;
}

export class CardDto implements ICardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;
    assignedUser?: UserDto | undefined;
    createdAt?: Date;
    updatedAt?: Date | undefined;

    constructor(data?: ICardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.boardColumnId = _data["boardColumnId"];
            this.description = _data["description"];
            this.order = _data["order"];
            this.assignedUserId = _data["assignedUserId"];
            this.assignedUser = _data["assignedUser"] ? UserDto.fromJS(_data["assignedUser"]) : <any>undefined;
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): CardDto {
        data = typeof data === 'object' ? data : {};
        let result = new CardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["boardColumnId"] = this.boardColumnId;
        data["description"] = this.description;
        data["order"] = this.order;
        data["assignedUserId"] = this.assignedUserId;
        data["assignedUser"] = this.assignedUser ? this.assignedUser.toJSON() : <any>undefined;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface ICardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;
    assignedUser?: UserDto | undefined;
    createdAt?: Date;
    updatedAt?: Date | undefined;
}

export class ApiResponseOfGetUserBoardResponse implements IApiResponseOfGetUserBoardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserBoardResponse | undefined;

    constructor(data?: IApiResponseOfGetUserBoardResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? GetUserBoardResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfGetUserBoardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfGetUserBoardResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfGetUserBoardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserBoardResponse | undefined;
}

export class ResponseOfUserBoardDto extends Response implements IResponseOfUserBoardDto {
    data?: UserBoardDto | undefined;

    constructor(data?: IResponseOfUserBoardDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? UserBoardDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): ResponseOfUserBoardDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfUserBoardDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfUserBoardDto extends IResponse {
    data?: UserBoardDto | undefined;
}

export class GetUserBoardResponse extends ResponseOfUserBoardDto implements IGetUserBoardResponse {

    constructor(data?: IGetUserBoardResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): GetUserBoardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetUserBoardResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IGetUserBoardResponse extends IResponseOfUserBoardDto {
}

export class ApiResponseOfCreateCardResponse implements IApiResponseOfCreateCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: CreateCardResponse | undefined;

    constructor(data?: IApiResponseOfCreateCardResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? CreateCardResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfCreateCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfCreateCardResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfCreateCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: CreateCardResponse | undefined;
}

export class ResponseOfCreateCardDto extends Response implements IResponseOfCreateCardDto {
    data?: CreateCardDto | undefined;

    constructor(data?: IResponseOfCreateCardDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? CreateCardDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): ResponseOfCreateCardDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfCreateCardDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfCreateCardDto extends IResponse {
    data?: CreateCardDto | undefined;
}

export class CreateCardResponse extends ResponseOfCreateCardDto implements ICreateCardResponse {

    constructor(data?: ICreateCardResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): CreateCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCardResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface ICreateCardResponse extends IResponseOfCreateCardDto {
}

export class CreateCardDto implements ICreateCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;

    constructor(data?: ICreateCardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.boardColumnId = _data["boardColumnId"];
            this.description = _data["description"];
            this.order = _data["order"];
            this.assignedUserId = _data["assignedUserId"];
        }
    }

    static fromJS(data: any): CreateCardDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["boardColumnId"] = this.boardColumnId;
        data["description"] = this.description;
        data["order"] = this.order;
        data["assignedUserId"] = this.assignedUserId;
        return data;
    }
}

export interface ICreateCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;
}

export class CreateCardCommand implements ICreateCardCommand {
    userId?: string;
    boardId?: string;
    boardColumnId?: string;
    description?: string | undefined;
    assignedUserId?: string | undefined;

    constructor(data?: ICreateCardCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.boardId = _data["boardId"];
            this.boardColumnId = _data["boardColumnId"];
            this.description = _data["description"];
            this.assignedUserId = _data["assignedUserId"];
        }
    }

    static fromJS(data: any): CreateCardCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCardCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["boardId"] = this.boardId;
        data["boardColumnId"] = this.boardColumnId;
        data["description"] = this.description;
        data["assignedUserId"] = this.assignedUserId;
        return data;
    }
}

export interface ICreateCardCommand {
    userId?: string;
    boardId?: string;
    boardColumnId?: string;
    description?: string | undefined;
    assignedUserId?: string | undefined;
}

export class ApiResponseOfUpdateCardResponse implements IApiResponseOfUpdateCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: UpdateCardResponse | undefined;

    constructor(data?: IApiResponseOfUpdateCardResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? UpdateCardResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfUpdateCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfUpdateCardResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfUpdateCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: UpdateCardResponse | undefined;
}

export class UpdateCardResponse extends Response implements IUpdateCardResponse {
    data?: UpdateCardDto | undefined;

    constructor(data?: IUpdateCardResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? UpdateCardDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): UpdateCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateCardResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IUpdateCardResponse extends IResponse {
    data?: UpdateCardDto | undefined;
}

export class UpdateCardDto implements IUpdateCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;

    constructor(data?: IUpdateCardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.boardColumnId = _data["boardColumnId"];
            this.description = _data["description"];
            this.order = _data["order"];
            this.assignedUserId = _data["assignedUserId"];
        }
    }

    static fromJS(data: any): UpdateCardDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateCardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["boardColumnId"] = this.boardColumnId;
        data["description"] = this.description;
        data["order"] = this.order;
        data["assignedUserId"] = this.assignedUserId;
        return data;
    }
}

export interface IUpdateCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;
}

export class UpdateCardCommand implements IUpdateCardCommand {
    userId?: string;
    cardId?: string;
    boardId?: string;
    description?: string | undefined;
    assignedUserId?: string | undefined;

    constructor(data?: IUpdateCardCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.cardId = _data["cardId"];
            this.boardId = _data["boardId"];
            this.description = _data["description"];
            this.assignedUserId = _data["assignedUserId"];
        }
    }

    static fromJS(data: any): UpdateCardCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateCardCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["cardId"] = this.cardId;
        data["boardId"] = this.boardId;
        data["description"] = this.description;
        data["assignedUserId"] = this.assignedUserId;
        return data;
    }
}

export interface IUpdateCardCommand {
    userId?: string;
    cardId?: string;
    boardId?: string;
    description?: string | undefined;
    assignedUserId?: string | undefined;
}

export class ApiResponseOfMoveCardResponse implements IApiResponseOfMoveCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: MoveCardResponse | undefined;

    constructor(data?: IApiResponseOfMoveCardResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? MoveCardResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfMoveCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfMoveCardResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfMoveCardResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: MoveCardResponse | undefined;
}

export class ResponseOfMoveCardDto extends Response implements IResponseOfMoveCardDto {
    data?: MoveCardDto | undefined;

    constructor(data?: IResponseOfMoveCardDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? MoveCardDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): ResponseOfMoveCardDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfMoveCardDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfMoveCardDto extends IResponse {
    data?: MoveCardDto | undefined;
}

export class MoveCardResponse extends ResponseOfMoveCardDto implements IMoveCardResponse {

    constructor(data?: IMoveCardResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): MoveCardResponse {
        data = typeof data === 'object' ? data : {};
        let result = new MoveCardResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IMoveCardResponse extends IResponseOfMoveCardDto {
}

export class MoveCardDto implements IMoveCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;

    constructor(data?: IMoveCardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.boardColumnId = _data["boardColumnId"];
            this.description = _data["description"];
            this.order = _data["order"];
            this.assignedUserId = _data["assignedUserId"];
        }
    }

    static fromJS(data: any): MoveCardDto {
        data = typeof data === 'object' ? data : {};
        let result = new MoveCardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["boardColumnId"] = this.boardColumnId;
        data["description"] = this.description;
        data["order"] = this.order;
        data["assignedUserId"] = this.assignedUserId;
        return data;
    }
}

export interface IMoveCardDto {
    id?: string;
    boardColumnId?: string;
    description?: string | undefined;
    order?: number;
    assignedUserId?: string | undefined;
}

export class MoveCardCommand implements IMoveCardCommand {
    userId?: string;
    cardId?: string;
    boardId?: string;
    targetBoardColumnId?: string;
    targetOrder?: number;

    constructor(data?: IMoveCardCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.cardId = _data["cardId"];
            this.boardId = _data["boardId"];
            this.targetBoardColumnId = _data["targetBoardColumnId"];
            this.targetOrder = _data["targetOrder"];
        }
    }

    static fromJS(data: any): MoveCardCommand {
        data = typeof data === 'object' ? data : {};
        let result = new MoveCardCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["cardId"] = this.cardId;
        data["boardId"] = this.boardId;
        data["targetBoardColumnId"] = this.targetBoardColumnId;
        data["targetOrder"] = this.targetOrder;
        return data;
    }
}

export interface IMoveCardCommand {
    userId?: string;
    cardId?: string;
    boardId?: string;
    targetBoardColumnId?: string;
    targetOrder?: number;
}

export class ApiResponseOfGetUserResponse implements IApiResponseOfGetUserResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserResponse | undefined;

    constructor(data?: IApiResponseOfGetUserResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? GetUserResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfGetUserResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfGetUserResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfGetUserResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUserResponse | undefined;
}

export class ResponseOfUserDto extends Response implements IResponseOfUserDto {
    data?: UserDto | undefined;

    constructor(data?: IResponseOfUserDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.data = _data["data"] ? UserDto.fromJS(_data["data"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): ResponseOfUserDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfUserDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["data"] = this.data ? this.data.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfUserDto extends IResponse {
    data?: UserDto | undefined;
}

export class GetUserResponse extends ResponseOfUserDto implements IGetUserResponse {

    constructor(data?: IGetUserResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): GetUserResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetUserResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IGetUserResponse extends IResponseOfUserDto {
}

export class ApiResponseOfGetUsersResponse implements IApiResponseOfGetUsersResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUsersResponse | undefined;

    constructor(data?: IApiResponseOfGetUsersResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.statusCode = _data["statusCode"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? ApiError.fromJS(_data["exception"]) : <any>undefined;
            this.result = _data["result"] ? GetUsersResponse.fromJS(_data["result"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ApiResponseOfGetUsersResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfGetUsersResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["statusCode"] = this.statusCode;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["result"] = this.result ? this.result.toJSON() : <any>undefined;
        return data;
    }
}

export interface IApiResponseOfGetUsersResponse {
    statusCode?: number;
    message?: string;
    exception?: ApiError;
    result?: GetUsersResponse | undefined;
}

export class ResponseOfListOfUserDto extends Response implements IResponseOfListOfUserDto {
    data?: UserDto[] | undefined;

    constructor(data?: IResponseOfListOfUserDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(UserDto.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): ResponseOfListOfUserDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResponseOfListOfUserDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item ? item.toJSON() : <any>undefined);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IResponseOfListOfUserDto extends IResponse {
    data?: UserDto[] | undefined;
}

export class GetUsersResponse extends ResponseOfListOfUserDto implements IGetUsersResponse {

    constructor(data?: IGetUsersResponse) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): GetUsersResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetUsersResponse();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IGetUsersResponse extends IResponseOfListOfUserDto {
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}